config/routes.rb
Rails.application.routes.draw do
	root 'orders#new'

  resources :restaurants, only: [:index] do
  	get :recap, on: :member
		resources :items
	  resources :orders, only: [:index, :destroy]
	end

	resources :orders, only: [:new, :create]
	
  devise_for :users
  
  mount ActionCable.server => '/cable'
end

app/models/order.rb
class Order < ApplicationRecord
	acts_as_paranoid

	belongs_to :restaurant
	has_many :line_items
	has_many :items, through: :line_items
	accepts_nested_attributes_for :items, allow_destroy: true

	validates_presence_of :restaurant_id
	validates_presence_of :section
	validates_presence_of :seat

	before_save :set_location
	before_save :set_number
	after_commit :broadcast_order, on: :create

	scope :completed, -> { only_deleted.where(cancelled: [nil, false]) }

	SECTION = ['A', 'B', 'C', 'D', 'E']

	def cancel
		update(cancelled: true)
	end

	def total
		items.pluck(:price).sum
	end

	private

		def broadcast_order
			html = ApplicationController.render(
				partial: 'orders/order', 
				locals: { order: self }
			)

		  ActionCable.server.broadcast "order_channel", { html: html }
		end

		def set_location
			self.location = ['A', 'B', 'C'].include?(section) ? 'BREW' : 'COMD'
		end

		def set_number
			last_order_id = Order.last&.id || 0
			order_number = last_order_id.to_s.last(3).to_i
			self.number = order_number
		end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:show, :edit, :update, :destroy]

  # GET /orders
  # GET /orders.json
  def index
    @restaurant = Restaurant.find(params[:restaurant_id])
    @orders = Order.where(restaurant: @restaurant).order(created_at: :asc)
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
  end

  # GET /orders/new
  def new
    @order = Order.new
    @order.items.build
  end

  # GET /orders/1/edit
  def edit
  end

  # POST /orders
  # POST /orders.json
  def create
    @order = Order.new(order_params)

    if items_attributes.nil?
      flash.now[:alert] = 'Missing items'
      return render :new
    end

    # Add item to the order
    build_items_for_order(items_attributes)

    # Set user_id to the sender's id
    @order.user_id = current_user.id

    if @order.save
      redirect_to new_order_path, notice: 'Order was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /orders/1
  # PATCH/PUT /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to @order, notice: 'Order was successfully updated.' }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @restaurant = Restaurant.find(params[:restaurant_id])

    @order.destroy
    
    if cancelled?
      @order.cancel
      return redirect_to restaurant_orders_path(restaurant: @restaurant), alert: 'Order cancelled'
    end

    redirect_to restaurant_orders_path(restaurant: @restaurant), notice: 'Order completed'
  end

  private
    def build_items_for_order(items_attributes)
      items_attributes.each do |_index, attributes|
        @order.line_items.build(
          order: @order, 
          item_id: attributes[:id], 
          notes: attributes[:notes])
      end
    end

    def cancelled?
      params[:cancelled] == 'true'
    end

    def items_attributes
      params[:items_attributes]
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_params
      params.require(:order).permit(:number, 
                                    :location, 
                                    :restaurant_id, 
                                    :user_id, 
                                    :section, 
                                    :seat
                                  )
    end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/_form.html.haml
= form_for order, :url => { :action => "create" } do |f|
  .row.errors
    .col-md-12
      - if order.errors.any?
        - order.errors.full_messages.each do |message|
          %p.alert.alert-danger 
            = message
  .row.new-order
    .col-md-3.section.location-selection
      .panel
        .field
          .row
            .col-md-12
              = f.label :restaurant_id
              %hr
            .col-md-12
              = f.select :restaurant_id, Restaurant.all.collect { |r| [ r.name, r.id ] }, prompt: 'Restaurant', selected: Restaurant.first&.id
      .panel
        .field
          .row
            .col-md-12
              = f.label :section
              %hr
            .col-md-12
              = f.select :section, Order::SECTION.collect { |section| [ section ] }, prompt: 'Section', selected: Order::SECTION.first
      .panel
        .field
          .row
            .col-md-12
              = f.label :seat
              %hr
            .col-md-12
              = f.select :seat, (1..50).collect { |s| [ s ] }, prompt: 'Seat'
    .col-md-5.items.section
      %label
        Items
      - Item.available.order(:name).each do |item|
        .panel{ id: item.id}
          .row
            .col-md-5.name
              = f.hidden_field :item_name, value: item.name
              = f.hidden_field :item_price, value: item.price
              = item.name
            .col-md-3.price
              = number_to_currency(item.price)
            .col-md-3
              %button.btn.btn-success{ type: "button", data: { action: 'add-item' } } Add Item

    #note-modal.modal.fade{"aria-hidden" => "true", role: "dialog", tabindex: "-1"}
      = f.hidden_field :line_item_index, value: 0
      .modal-dialog{:role => "document"}
        .modal-content
          .modal-header
            %h5#exampleModalLabel.modal-title Add Note
            %button.close{"aria-label" => "Close", "data-dismiss" => "modal", type: "button"}
              %span{"aria-hidden" => "true"} ×
          .modal-body
            .row
              .col-md-12
                %p This note will be attached to the item.
              .col-md-12
                = text_area_tag 'item_attributes[][notes]', nil, class: 'note'
          .modal-footer
            %button.btn.btn-primary.save{type: "button"} Save

    .col-md-4.current-sale.section
      .panel
        .row
          .col-md-8
            %label
              Current Sale
          .col-md-3.total
            %label
              $0.00
        %hr
        .items
          - @order&.line_items.each_with_index do |line_item, index|
            .row.sale-item{ id: index }
              %input{ name: "items_attributes[#{index}][id]", type: "hidden", value: line_item.item.id }/
              %input{ class: "note-#{index} note-text", name: "items_attributes[#{index}][notes]", type: "hidden", value: line_item.notes }/
              .col-md-6.item-name
                = line_item.name
              .col-md-6.text-right
                %i.fa.fa-times.fa-2x.delete-item
              .col-md-12.price
                = number_to_currency(line_item.price)
              .col-md-12.add-note{ data: { toggle: "modal", target: "#note-modal"} }
                %a
                  + Add Note
      .row
        .text-center.col-md-12.actions
          %button.btn.btn-primary.big-blue-btn{ type: "submit", data: { action: 'complete-order' } } 
            Send Order
            = fa_icon "chevron-circle-right"

:javascript
  console.log('hello from _form')
  $(document).ready(function() {
    // Calculate the total when arriving to the screen
    calculateTotal()

    // Everytime a modal is shown. Autofocus.
    $('#note-modal').on('shown.bs.modal', function () {
      $('#note-modal textarea').focus()
    })

    // Delete Item
    $('body').on('click', '.delete-item', function() {
      $(this).closest('.row.sale-item').remove()
      calculateTotal()
    })

    // Set line item index. This changes the hidden field everyt ime .add-note is
    // clicked. After a note is saved, it looks to this hidden field for guidance
    // as to which line item to save the note.
    $(".add-note").click(function() {
      let index = $(this).closest('.sale-item').attr('id')
      let text = $(this).closest('.sale-item').find('.note-text').val()
      $('#order_line_item_index').val(index)

      $('#note-modal textarea').val(text)
    });

    // Save Note. Using the lineItemIndex, save the text on the note hidden field that will
    // be passed to the back end.
    $(".save").click(function() {
      let textBox = $(this).parent().prev().find('textarea')
      let lineItemIndex = $('#order_line_item_index').val()
      let noteField = $(`.note-${lineItemIndex}`).val(textBox.val())

      // close modal
      $('.modal').modal('toggle');

      // clear textbox
      textBox.val('')
    });

    // Add Item to Order
    $("[data-action='add-item']").click(function() {
      // If there are already line items present then start at the appropriate index. For
      // example, if there are 3 line items, then add the new item with index 3 (0, 1, 2, 3)
      // for 4 total items in the current sale.
      let totalSaleItems = $('.sale-item').length

      const itemId = $(this).closest('.panel').attr('id')
      const itemName = $(this).closest('.row').find("[name='order[item_name]']").val()
      const itemPrice = parseFloat(
                    $(this)
                    .closest('.row')
                    .find("[name='order[item_price]']")
                    .val())
                    .toFixed(2)

      const itemNameHTML = `<div class='row sale-item' id='${totalSaleItems}'>` +
                      "<div class='col-md-6 item-name'>" + 
                        itemName + 
                      "</div>" + 
                      "<div class='col-md-6 text-right'>" +
                        "<i class='fa fa-times fa-2x delete-item'></i>" +
                      "</div>" +
                      "<div class='col-md-12 price'>" +
                        `$${itemPrice}` +
                      "</div>" +

                      "<div class='col-md-12 add-note' data-toggle='modal' data-target='#note-modal'>" +
                        '<a>' +
                          '+ Add Note'
                        '</a>' +
                      "</div>"

      $('.current-sale .items').append(itemNameHTML)

      $('<input>').attr({
        type: 'hidden',
        name: `items_attributes[${totalSaleItems}][id]`,
        value: itemId
      }).appendTo($( '.sale-item' ).last());

      $('<input>').attr({
        type: 'hidden',
        name: `items_attributes[${totalSaleItems}][notes]`,
        class: `note-${totalSaleItems} note-text`,
        value: ''
      }).appendTo($( '.sale-item' ).last());

      refreshEventListener();

      calculateTotal()
    });

    function refreshEventListener() {
      // on.click() wasn't working for dynamically added items
      // so the event listeners are reset every time an item is added
      $(".delete-item").off(); 

      $(".delete-item").on("click", function() {
        $(this).closest('.row.item').remove()
      })

      $(".add-note").off(); 

      $(".add-note").on("click", function() {
        let index = $(this).closest('.sale-item').attr('id')
        let text = $(this).closest('.sale-item').find('.note-text').val()
        $('#order_line_item_index').val(index)

        $('#note-modal textarea').val(text)
      })
    }

    function calculateTotal() {
      const salePrices = $('.sale-item')
      let total = 0.00

      $('.sale-item').each(function(i, obj) {
        const itemPriceString = $(obj).find('.price').text()
        
        const itemPriceFloat = parseFloat(itemPriceString.replace(/\$/g, ''))
        total += itemPriceFloat
      });

      $('.total').html(`<label>$${total.toFixed(2)}</label>`)
    }
  });

app/views/orders/_line_items.html.haml
- line_items = order.line_items.sort_by { |li| li.item.name }
- grouped_line_items = line_items.group_by(&:item_id)


- grouped_line_items.each do |item_id, line_items|  
  - line_items_with_notes = line_items.select { |li| li.notes.present? }
  - line_items_without_notes = line_items.reject { |li| li.notes.present? }

  / Show line_items with notes (for this item) individually
  - line_items_with_notes.each do |line_item|
    .row
      .col-md-6.item-name
        = "(1) #{line_item.item.name}"
      .col-md-6.item-notes
        = line_item.notes
    %hr

  / Group all the line_items without notes (for this item) together
  - if line_items_without_notes.present?
    .row
      .col-md-6.item-name
        = "(#{line_items_without_notes.count}) #{line_items.first.item.name}"
    %hr

app/views/orders/_order.html.haml
.row.order
  .col-md-12
    .panel
      .row.details
        .col-md-10.header
          = "##{order.number} #{order.location} - #{order.section}#{order.seat} (#{order.created_at.in_time_zone('Eastern Time (US & Canada)').strftime("%-l:%M %p")})"
          %span{ data: { action: 'cancel-order' } } 
            = link_to restaurant_order_path(order.restaurant, order, cancelled: true), method: :delete, class: 'cancel-order' do
              Cancel Order
        .col-md-2.text-right
          = link_to restaurant_order_path(order.restaurant, order), method: :delete do
            %button.btn.btn-primary{ type: "button", class: 'complete-btn', data: { action: 'complete-order' } } 
              = fa_icon "check-circle", text: 'Done'
      %hr
      .items
        .row.header
          .col-md-6
            Item
        = render partial: 'orders/line_items', locals: { order: order }
        .row.total
          .col-md-1
            %label
              Total:
          .col-md-1
            %label
              = number_to_currency(order.total)

app/views/orders/edit.html.erb
<h1>Editing Order</h1>

<%= render 'form', order: @order %>

<%= link_to 'Show', @order %> |
<%= link_to 'Back', orders_path %>

app/views/orders/index.html.haml
.row.hidden#topbar
	.col-md-12.text-center
		.alert.alert-success
			New order! Order details will appear at the bottom of the page.
%h1 Orders
.orders
	- @orders.each do |order|
		= render partial: 'order', locals: { order: order, restaurant: @restaurant }

app/views/orders/new.html.erb
<%= render 'form', order: @order %>

app/views/orders/new.html.haml
.row.hidden.completed-order.topbar
	.col-md-12.text-center
		.alert.alert-success.completed-order
			Order's Up! Food is ready!
= render 'form', order: @order

app/views/orders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Number:</strong>
  <%= @order.number %>
</p>

<p>
  <strong>Location:</strong>
  <%= @order.location %>
</p>

<p>
  <strong>Restaurant:</strong>
  <%= @order.restaurant_id %>
</p>

<p>
  <strong>User:</strong>
  <%= @order.user_id %>
</p>

<p>
  <strong>Section:</strong>
  <%= @order.section %>
</p>

<p>
  <strong>Seat:</strong>
  <%= @order.seat %>
</p>

<%= link_to 'Edit', edit_order_path(@order) %> |
<%= link_to 'Back', orders_path %>