config/routes.rb
Rails.application.routes.draw do
	root 'orders#new'

  resources :restaurants, only: [:index] do
  	get :recap, on: :member
		resources :items
	  resources :orders, only: [:index, :destroy]
	end

	resources :orders, only: [:new, :create]
	
  devise_for :users
  
  mount ActionCable.server => '/cable'
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
	has_many :orders
	has_many :items
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: [:show, :edit, :update, :destroy]

  # GET /restaurants
  # GET /restaurants.json
  def index
    @restaurants = Restaurant.all
  end

  def recap
    @restaurant = Restaurant.find(params[:id])
    orders = @restaurant.orders.completed

    @orders_by_day = orders.group_by_day(&:created_at).to_a.reverse.to_h
  end

  # GET /restaurants/1
  # GET /restaurants/1.json
  def show
  end

  # GET /restaurants/new
  def new
    @restaurant = Restaurant.new
  end

  # GET /restaurants/1/edit
  def edit
  end

  # POST /restaurants
  # POST /restaurants.json
  def create
    @restaurant = Restaurant.new(restaurant_params)

    respond_to do |format|
      if @restaurant.save
        format.html { redirect_to @restaurant, notice: 'Restaurant was successfully created.' }
        format.json { render :show, status: :created, location: @restaurant }
      else
        format.html { render :new }
        format.json { render json: @restaurant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /restaurants/1
  # PATCH/PUT /restaurants/1.json
  def update
    respond_to do |format|
      if @restaurant.update(restaurant_params)
        format.html { redirect_to @restaurant, notice: 'Restaurant was successfully updated.' }
        format.json { render :show, status: :ok, location: @restaurant }
      else
        format.html { render :edit }
        format.json { render json: @restaurant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /restaurants/1
  # DELETE /restaurants/1.json
  def destroy
    @restaurant.destroy
    respond_to do |format|
      format.html { redirect_to restaurants_url, notice: 'Restaurant was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_restaurant
      @restaurant = Restaurant.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def restaurant_params
      params.require(:restaurant).permit(:name)
    end
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/restaurants/_form.html.haml
= form_for(restaurant) do |f|
  - if restaurant.errors.any?
    #error_explanation
      %h2
        = pluralize(restaurant.errors.count, "error")
        prohibited this restaurant from being saved:
      %ul
        - restaurant.errors.full_messages.each do |message|
          %li= message
  .row.custom-form
    .col-md-3.section
      .panel
        .field
          .row
            .col-md-12
              = f.label :name
              %hr
            .col-md-12
              = f.text_field :name
  .row{ style: 'margin-top: 20px;' }
    .text-center.col-md-3
      %button.btn.btn-primary.big-blue-btn{ type: "submit" }
        = "#{restaurant.persisted? ? 'Update Restaurant' : 'Create Restaurant'}"

app/views/restaurants/edit.html.erb
<h1>Editing Restaurant</h1>

<%= render 'form', restaurant: @restaurant %>

app/views/restaurants/index.html.haml
%p#notice= notice
.item-index
  .row.header
    .col-md-9
      %h1 Restaurants
%table.table.table-striped
  %thead
    %tr
      %th Restaurant Name
      %th Orders
      %th Items
      %th Recap
  %tbody
    - @restaurants.each do |restaurant|
      %tr
        %td= restaurant.name
        %td= link_to 'Orders', restaurant_orders_path(restaurant)
        %td= link_to 'Items', restaurant_items_path(restaurant)
        %td= link_to 'Recap', recap_restaurant_path(restaurant)

app/views/restaurants/new.html.erb
<h1>New Restaurant</h1>

<%= render 'form', restaurant: @restaurant %>

app/views/restaurants/recap.html.haml
%h1 Recap
- @orders_by_day.each do |date, orders|
  %table.table.table-striped.recap-table{ data: { section: date.strftime("%m/%d/%Y") } }
    %thead
      %tr
        %th Date
        %th Time
        %th Order Number
        %th Location
        %th Section
        %th Seat
        %th Total
    %tbody
      - orders.sort_by(&:created_at).each do |order|
        - created_at = order.created_at.in_time_zone('Eastern Time (US & Canada)')
        %tr
          %td
            = created_at.strftime("%m/%d/%Y")
          %td
            = created_at.strftime("%-l:%M %p")
          %td
            = "##{order.number}" 
          %td
            = order.location 
          %td
            = order.section
          %td
            = order.seat
          %td
            = number_to_currency(order.total)
      %tr
        %td
        %td
        %td
        %td
        %td
        %td.total
          TOTAL
        %td.total
          - total = 0
          - orders.each do |order|
            - total += order.items.pluck(:price).sum
          = number_to_currency(total)

app/views/restaurants/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @restaurant.name %>
</p>

<%= link_to 'Edit', edit_restaurant_path(@restaurant) %> |
<%= link_to 'Back', restaurants_path %>