config/routes.rb
Rails.application.routes.draw do
	root 'orders#new'

  resources :restaurants, only: [:index] do
  	get :recap, on: :member
		resources :items
	  resources :orders, only: [:index, :destroy]
	end

	resources :orders, only: [:new, :create]
	
  devise_for :users
  
  mount ActionCable.server => '/cable'
end

app/models/item.rb
class Item < ApplicationRecord
	acts_as_paranoid

	belongs_to :restaurant
	has_many :line_items
	has_many :orders, through: :line_items

	validates_presence_of :name
	validates_presence_of :price

	scope :available, -> { where(sold_out: [nil, false]) }

	def available?
		!sold_out?
	end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]
  before_action :set_restaurant

  def index
    @items = Item.where(restaurant: @restaurant).order(:name)
  end

  def show
  end

  def new
    @item = Item.new
  end

  def edit
  end

  def create
    item = @restaurant.items.new(item_params)

    respond_to do |format|
      if item.save
        format.html { redirect_to restaurant_items_path(@restaurant), notice: 'Item was successfully created.' }
        format.json { render :show, status: :created, location: item }
      else
        format.html { render :new }
        format.json { render json: item.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to restaurant_items_path(@restaurant), notice: 'Item was successfully updated.' }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to restaurant_items_path(@restaurant), notice: 'Item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    
    def set_item
      @item = Item.find(params[:id])
    end

    def set_restaurant
      @restaurant = Restaurant.find(params[:restaurant_id])
    end

    def item_params
      price = params[:item][:price].to_s.gsub(/[^\d.]/, '')
      params[:item][:price] = price

      params.require(:item).permit(:name, :price, :sold_out)
    end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.html.haml
= form_for ([restaurant, item]) do |f|
  - if item.errors.any?
    #error_explanation
      %h2
        = pluralize(item.errors.count, "error")
        prohibited this item from being saved:
      %ul
        - item.errors.full_messages.each do |message|
          %li= message
  .row.custom-form
    .col-md-3.section
      .panel
        .field
          .row
            .col-md-12
              = f.label :sold_out?
              %hr
            .col-md-12.sold-out-btn-group
              .btn-group.btn-group-toggle{"data-toggle" => "buttons"}
                %label.btn.btn-secondary{ class: "#{'active' if item.sold_out?} " }
                  = f.radio_button :sold_out, true, :checked => item.sold_out?, autocomplete: "off"
                  Yes
                %label.btn.btn-secondary{ class: "#{'active' if item.available?} " }
                  = f.radio_button :sold_out, false, :checked => item.available?, autocomplete: "off"
                  No
    .col-md-3.section
      .panel
        .field
          .row
            .col-md-12
              = f.label :name
              %hr
            .col-md-12
              = f.text_field :name
    .col-md-3.section
      .panel
        .field
          .row
            .col-md-12
              = f.label :price
              %hr
            .col-md-12
              = f.text_field :price, value: number_with_precision(item.price, :precision => 2)
  .row{ style: 'margin-top: 20px;' }
    .text-center.col-md-3
      %button.btn.btn-primary.big-blue-btn{ type: "submit" }
        = "#{item.persisted? ? 'Update Item' : 'Create Item'}"

app/views/items/edit.html.erb
<h1>Editing Item</h1>

<%= render 'form', item: @item, restaurant: @restaurant %>

app/views/items/index.html.haml
.item-index
  .row.header
    .col-md-9
      %h1 Items
    .col-md-3
      = link_to "<i class='fa fa-plus-circle' style='padding-right: 10px'></i> New Item".html_safe, new_restaurant_item_path(@restaurant), class: 'btn btn-primary big-blue-btn', style: 'padding-top: 10px;'
  %table.table.table-striped
    %thead
      %tr
        %th{ scope: 'col'} #
        %th{ scope: 'col'} Name
        %th{ scope: 'col'} Price
        %th{ scope: 'col'} Sold Out?
        %th{ scope: 'col'} Delete
    %tbody
      - @items.each_with_index do |item, index|
        %tr
          %th{ scope: 'row'}= (index + 1)
          %td
            = link_to item.name, edit_restaurant_item_path(@restaurant, item)
          %td
            = number_to_currency(item.price)
          %td
            = item.sold_out? ? 'Yes' : 'No'
          %td
            = link_to "<i style='color: red' class='fa fa-times fa-2x'></i>".html_safe, restaurant_item_path(@restaurant, item), method: :delete, data: { confirm: 'Are you sure?' }

app/views/items/new.html.erb
<h1>New Item</h1>

<%= render 'form', item: @item, restaurant: @restaurant %>

app/views/items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @item.name %>
</p>

<p>
  <strong>Price:</strong>
  <%= @item.price %>
</p>

<p>
  <strong>Restaurant:</strong>
  <%= @item.restaurant_id %>
</p>

<p>
  <strong>Sold Out:</strong>
  <%= @item.sold_out? %>
</p>

<%= link_to 'Edit', edit_item_path(@item) %> |
<%= link_to 'Back', restaurant_items_path %>